apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: 2apps/overlays/blue
    repoURL: https://github.com/tivolinick/argoplay
    targetRevision: master
  destination:
    namespace: blue
    server: https://api.ndfargo.cp.fyre.ibm.com:6443
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

