apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: bgd
  path: green-deployment.yaml
- target:
    version: v1
    kind: Namespace
    name: bgd
  path: green-namespace.yaml
- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: bgd
  path: green-route.yaml

